### ISSUE TITLE
Cyrillic support

### ISSUE THREAD

**Issue by marchellodev** [shah-xad/flutter_tex#59] opened 2020-06-06 14:50 UTC
```
TeXView(
      child: TeXViewDocument(
        r'''$$\frac{1}{2}! \neq \frac{1}{2}$$ here is some english | тут кирилиця''',
      ),
    );
```

![Screenshot from 2020-06-06 17-49-34](https://user-images.githubusercontent.com/61112084/83947167-1b604280-a81e-11ea-9667-d95f34f1b73c.png)

**Comment by marchellodev** [comment] 2020-06-06 14:53
probably related to https://github.com/shah-xad/flutter_tex/issues/58

**Comment by j33tmane** [comment] 2020-06-06 18:29
need support for other than English languages( charset UTF-8)

**Comment by shah-xad** [comment] 2020-06-06 19:23
Trying to sort out the issue and closing it as a duplicate of #58

**Closed by shah-xad** 2020-06-06 19:23 UTC

**Comment by shah-xad** [comment] 2020-06-07 07:59
Thanks for your support for making the flutter_tex package better by pointing towards this issue. Now, this issue has been resolved please consider the latest version of the package.
