### ISSUE TITLE
Render mathml

### ISSUE THREAD

**Issue by blizzy312** [shah-xad/flutter_tex#47] opened 2020-05-14 05:41 UTC
Hey, I'd like to know, whether it is possible to render mathml format?
Something like this:
`<p><math xmlns="http://www.w3.org/1998/Math/MathML"><msqrt><msub><mn>4</mn><mn>3</mn></msub></msqrt></math></p>`
I've tried to change render engine to 'mathjax', but no luck...
Thanks.

**Comment by shah-xad** [comment] 2020-05-17 13:17
This issue is Duplicate of #25 .

**Closed** 2020-05-17 13:17 UTC
Labels: duplicate
